version: "3.8"

services:
    db:
        image: postgres:latest
        container_name: go-banking-db
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
